version: "3.3"
services:
  traefik:
    image: traefik:latest
    restart: always
    volumes:
      -./traefik.yml:/etc/traefik/traefik.yml
    ports:
      - 8000:8000
      - 80:80
      - 443:443
  plausible:
    labels:
      traefik.enable: "true"
      traefik.http.routers.plausible.rule: "Host(`example.com`)" # change to your domain name
      traefik.http.routers.plausible.entrypoints: "websecure"
      traefik.http.services.plausible.loadbalancer.server.port: "8000"
