version: "3.3"
services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro

  plausible:
    labels:
      traefik.enable: "true"
      traefik.http.routers.plausible.rule: "Host(`plausible.henriktech.com`)" # change to your domain name
      traefik.http.routers.plausible.tls.certResolver: "primary"
      traefik.http.routers.plausible.entrypoints: "websecure"
      traefik.http.services.plausible.loadbalancer.server.port: "8000"
